apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-inspire-app
  labels:
    app: team-inspire-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-inspire-app
  template:
    metadata:
      labels:
        app: team-inspire-app
    spec:
      containers:
        - name: team-inspire-app
          image: team-inspire-app:v1
          env:
            - name: PORT
              value: "4000"
          ports:
            - containerPort: 4000
              name: inspire-p
