apiVersion: skaffold/v1beta14
kind: Config
build:
  artifacts:
  - image: team-basket-text
    context: src/team-basket-text
  - image: team-composite-app
    context: src/team-composite
  - image: team-inspire-text
    context: src/team-inspire-text
  - image: team-product-text
    context: src/team-product-text
  - image: team-search-text
    context: src/team-search-text
deploy:
  kubectl:
    manifests:
    - src/team-basket-text/team-basket-text.deployment-service.yml
    - src/team-composite/team-composite-app.deployment-service.yml
    - src/team-inspire-text/team-inspire-text.deployment-service.yml
    - src/team-product-text/team-product-text.deployment-service.yml
    - src/team-search-text/team-search-text.deployment-service.yml
