apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-product-app
  labels:
    app: team-product-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-product-app
  template:
    metadata:
      labels:
        app: team-product-app
    spec:
      containers:
        - name: team-product-app
          image: team-product-app:v1
          env:
            - name: PORT
              value: "5000"
          ports:
            - containerPort: 5000
              name: product-p
